/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NMcHuRbVUAM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function Filter2() {
  return (
    <div className="max-w-full mx-auto p-4 bg-white rounded-md shadow-md">
      <div className="flex justify-center space-x-4 mb-4">
        <Button variant="default" className="bg-[#f0c14b] text-black">
          NATURAL DIAMONDS
        </Button>
        <Button variant="outline">LAB GROWN DIAMONDS</Button>
      </div>
      <div className="flex justify-center space-x-4 mb-4">
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="All"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>All</span>
        </div>
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="Round"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>Round</span>
        </div>
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="Princess"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>Princess</span>
        </div>
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="Emerald"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>Emerald</span>
        </div>
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="Pear"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>Pear</span>
        </div>
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="Heart"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>Heart</span>
        </div>
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="Oval"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>Oval</span>
        </div>
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="Marquise"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>Marquise</span>
        </div>
        <div className="flex flex-col items-center">
          <img
            src="/placeholder.svg"
            alt="Radiant"
            width="50"
            height="50"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <span>Radiant</span>
        </div>
      </div>
      <div className="grid grid-cols-1 gap-4 mb-4 md:grid-cols-2 lg:grid-cols-3">
        <div className="flex flex-col space-y-2">
          <Label>Quality</Label>
          <div className="flex space-x-2">
            <Button variant="outline">BEST</Button>
            <Button variant="outline">MEDIUM</Button>
            <Button variant="outline">LOW</Button>
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <Label>Price</Label>
          <div className="flex space-x-2">
            <Input placeholder="₹ From" />
            <Input placeholder="₹ To" />
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <Label>Carat</Label>
          <div className="flex space-x-2">
            <Input placeholder="From" />
            <Input placeholder="To" />
            <Input placeholder="Stock No." />
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <Label>Color</Label>
          <div className="flex space-x-2">
            <Button variant="outline">White</Button>
            <Button variant="outline">Fancy</Button>
          </div>
          <div className="grid grid-cols-8 gap-2">
            {["D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O-P", "Q-R", "S-T", "U-V", "W-X", "Y-Z"].map(
              (color) => (
                <Button variant="outline" key={color}>
                  {color}
                </Button>
              ),
            )}
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <Label>Clarity</Label>
          <div className="grid grid-cols-4 gap-2">
            {["FL", "IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2", "I1", "I2", "I3"].map((clarity) => (
              <Button variant="outline" key={clarity}>
                {clarity}
              </Button>
            ))}
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <Label>Certificate</Label>
          <div className="grid grid-cols-4 gap-2">
            {["GIA", "IGI", "HRD", "SGL", "FM", "GCAL", "GSI", "Other"].map((cert) => (
              <Button variant="outline" key={cert}>
                {cert}
              </Button>
            ))}
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <Label>Fluorescence</Label>
          <div className="grid grid-cols-5 gap-2">
            {["None", "Faint", "Medium", "Strong", "V-Strong"].map((fluor) => (
              <Button variant="outline" key={fluor}>
                {fluor}
              </Button>
            ))}
          </div>
        </div>
        <div className="flex flex-col space-y-2">
          <Label>Make</Label>
          <div className="grid grid-cols-3 gap-2">
            {["3EX", "EX CUT", "3 VG+"].map((make) => (
              <Button variant="outline" key={make}>
                {make}
              </Button>
            ))}
          </div>
       
        </div>
        <div className="flex flex-col space-y-2">
            <Label>Returnable</Label>
            <Button variant="outline">Yes</Button>
            <Button variant="outline">No</Button>
          </div>
      </div>
      <div className="flex justify-center space-x-4 mb-4">
        <Button className="bg-[#5c3d91] text-white">SEARCH DIAMONDS</Button>
        <Button variant="outline">ADVANCE FILTERS</Button>
        <Button variant="outline">RESET FILTER</Button>
      </div>
      <div className="text-center">
        <p className="text-sm">
          Are you a jeweller? Get discounted trade prices after{" "}
          <a href="#" className="text-blue-600">
            Login/signup
          </a>
          .
        </p>
      </div>
    </div>
  )
}
